springdoc:
  swagger-ui:
    oauth:
      client-id: 1011052694596-41c27fopgo92m809li62rhfeetl0p709.apps.googleusercontent.com
      client-secret: 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
      use-basic-authentication-with-access-code-grant: true
      use-pkce-with-authorization-code-grant: false
    path: /swagger-ui.html
    csrf:
      enabled: false
  api-docs:
    path: /v3/api-docs

spring:
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/finley_db
    username: finley_user
    password: finley_password
    pool:
      initial-size: 5
      max-size: 20
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false